version: '3'

services:
  message-service:
    image: message-service:latest

  user-service:
    image: user-service:latest
    command:
      "--mysql.address=192.168.0.131"

  user-edge-service:
    image: user-edge-service:latest
    links:
      - user-service
    command:
      "--redis.address=192.168.164.15"

  api-gateway-zuul:
    image: api-geteway-zuul:latest
    links:
      - user-edge-service
    ports:
    - 8080:8080

  redis:
    image: redis:5.0.9
    ports:
    - 6379:6379
